package com.mycompany.atividadeaula6chat;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class TelaChat extends javax.swing.JFrame {

    private Socket socket;
    private PrintWriter saida;
    private String apelido;

    /**
     * Creates new form TelaChat
     */
    public TelaChat() {
        initComponents();
        atualizarEstadoConectado(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTopo = new javax.swing.JPanel();
        lblApelido = new javax.swing.JLabel();
        tfApelido = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        scrollChat = new javax.swing.JScrollPane();
        taChat = new javax.swing.JTextArea();
        painelBaixo = new javax.swing.JPanel();
        painelDestino = new javax.swing.JPanel();
        lblDestino = new javax.swing.JLabel();
        tfDestino = new javax.swing.JTextField();
        tfMensagem = new javax.swing.JTextField();
        painelBotoes = new javax.swing.JPanel();
        btnTodos = new javax.swing.JButton();
        btnPrivada = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnArquivo = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat TCP");
        getContentPane().setLayout(new java.awt.BorderLayout());

        lblApelido.setText("Apelido:");
        painelTopo.add(lblApelido);

        tfApelido.setColumns(12);
        painelTopo.add(tfApelido);

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(this::btnConectarActionPerformed);
        painelTopo.add(btnConectar);

        getContentPane().add(painelTopo, java.awt.BorderLayout.NORTH);

        taChat.setEditable(false);
        taChat.setColumns(20);
        taChat.setRows(5);
        taChat.setLineWrap(true);
        scrollChat.setViewportView(taChat);

        getContentPane().add(scrollChat, java.awt.BorderLayout.CENTER);

        painelBaixo.setLayout(new java.awt.BorderLayout());

        lblDestino.setText("Destino (so p/ Privada):");
        painelDestino.add(lblDestino);

        tfDestino.setColumns(10);
        painelDestino.add(tfDestino);

        painelBaixo.add(painelDestino, java.awt.BorderLayout.NORTH);

        tfMensagem.addActionListener(this::tfMensagemActionPerformed);
        painelBaixo.add(tfMensagem, java.awt.BorderLayout.CENTER);

        btnTodos.setText("Enviar Todos");
        btnTodos.addActionListener(this::btnTodosActionPerformed);
        painelBotoes.add(btnTodos);

        btnPrivada.setText("Enviar Privada");
        btnPrivada.addActionListener(this::btnPrivadaActionPerformed);
        painelBotoes.add(btnPrivada);

        btnListar.setText("Listar");
        btnListar.addActionListener(this::btnListarActionPerformed);
        painelBotoes.add(btnListar);

        btnArquivo.setText("Enviar Arquivo");
        btnArquivo.addActionListener(this::btnArquivoActionPerformed);
        painelBotoes.add(btnArquivo);

        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);
        painelBotoes.add(btnSair);

        painelBaixo.add(painelBotoes, java.awt.BorderLayout.SOUTH);

        getContentPane().add(painelBaixo, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // abre a conexao com o servidor e manda o apelido como primeira linha
    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        apelido = tfApelido.getText().trim();
        if (apelido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um apelido.");
            return;
        }
        try {
            socket = new Socket("localhost", 9999);
            saida = new PrintWriter(socket.getOutputStream(), true);
            BufferedReader entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            saida.println(apelido);
            new Thread(() -> receberMensagens(entrada)).start();
            atualizarEstadoConectado(true);
            log("Conectado como " + apelido + ". Use os botoes abaixo.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Nao foi possivel conectar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    // manda a mensagem digitada pra todo mundo conectado
    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        String texto = tfMensagem.getText().trim();
        if (texto.isEmpty()) {
            return;
        }
        saida.println(new Mensagem("BROADCAST", apelido, null, texto).paraLinha());
        tfMensagem.setText("");
    }//GEN-LAST:event_btnTodosActionPerformed

    // manda a mensagem so pro apelido preenchido em "destino"
    private void btnPrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrivadaActionPerformed
        String destino = tfDestino.getText().trim();
        String texto = tfMensagem.getText().trim();
        if (destino.isEmpty() || texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o destino e a mensagem.");
            return;
        }
        saida.println(new Mensagem("PRIVADA", apelido, destino, texto).paraLinha());
        tfMensagem.setText("");
    }//GEN-LAST:event_btnPrivadaActionPerformed

    // pede pro servidor a lista de quem esta conectado agora
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        saida.println(new Mensagem("LISTAR", apelido, null, null).paraLinha());
    }//GEN-LAST:event_btnListarActionPerformed

    // bonus: abre um ServerSocket, manda so o convite (ip/porta) e espera a conexao direta
    private void btnArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquivoActionPerformed
        String destino = tfDestino.getText().trim();
        if (destino.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o destino (apelido de quem vai receber).");
            return;
        }
        JFileChooser seletor = new JFileChooser();
        int escolha = seletor.showOpenDialog(this);
        if (escolha != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File arquivo = seletor.getSelectedFile();
        try {
            ServerSocket servidorArquivo = new ServerSocket(0);
            servidorArquivo.setSoTimeout(30000);
            String meuIp = socket.getLocalAddress().getHostAddress();
            int minhaPorta = servidorArquivo.getLocalPort();

            Mensagem convite = Mensagem.novaOfertaArquivo(apelido, destino, arquivo.getName(),
                    arquivo.length(), meuIp, minhaPorta);
            saida.println(convite.paraLinha());

            log("Convite enviado para " + destino + ". Aguardando conexao direta para enviar \""
                    + arquivo.getName() + "\"...");
            new Thread(() -> aguardarConexaoDireta(servidorArquivo, arquivo, destino)).start();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Nao foi possivel preparar o envio: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnArquivoActionPerformed

    // avisa o servidor que esta saindo e fecha a conexao
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try {
            saida.println(new Mensagem("SAIR", apelido, null, null).paraLinha());
            socket.close();
        } catch (IOException ex) {
        }
        atualizarEstadoConectado(false);
        log("Voce saiu do chat.");
    }//GEN-LAST:event_btnSairActionPerformed

    // Enter no campo de mensagem = mesmo efeito do botao Enviar Todos
    private void tfMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMensagemActionPerformed
        btnTodosActionPerformed(evt);
    }//GEN-LAST:event_tfMensagemActionPerformed

    // liga/desliga os controles de acordo com o estado da conexao
    private void atualizarEstadoConectado(boolean conectado) {
        tfApelido.setEnabled(!conectado);
        btnConectar.setEnabled(!conectado);
        tfDestino.setEnabled(conectado);
        tfMensagem.setEnabled(conectado);
        btnTodos.setEnabled(conectado);
        btnPrivada.setEnabled(conectado);
        btnListar.setEnabled(conectado);
        btnArquivo.setEnabled(conectado);
        btnSair.setEnabled(conectado);
    }

    private void log(String texto) {
        taChat.append(texto + "\n");
    }

    // roda na thread de leitura, fica esperando mensagem por mensagem
    private void receberMensagens(BufferedReader entrada) {
        try {
            String linha;
            while ((linha = entrada.readLine()) != null) {
                Mensagem msg = Mensagem.fromLinha(linha);

                if ("ARQUIVO".equals(msg.tipo)) {
                    new Thread(() -> receberOfertaArquivo(msg)).start();
                    continue;
                }

                String texto = formatar(msg);
                SwingUtilities.invokeLater(() -> log(texto));
            }
        } catch (IOException ex) {
            SwingUtilities.invokeLater(() -> {
                log("Conexao encerrada.");
                atualizarEstadoConectado(false);
            });
        }
    }

    private String formatar(Mensagem msg) {
        if ("RESPOSTA".equals(msg.tipo) && msg.lista != null) {
            return "Usuarios conectados: " + msg.lista;
        }
        if ("ERRO".equals(msg.tipo)) {
            return "[ERRO] " + msg.texto;
        }
        if ("PRIVADA".equals(msg.tipo)) {
            return "(privado) " + msg.remetente + ": " + msg.texto;
        }
        return msg.remetente + ": " + msg.texto;
    }

    // bonus: confirma com o usuario e baixa por conexao direta com quem enviou
    private void receberOfertaArquivo(Mensagem oferta) {
        int resposta = JOptionPane.showConfirmDialog(this,
                oferta.remetente + " quer te enviar o arquivo \"" + oferta.nomeArquivo
                + "\" (" + oferta.tamanhoArquivo + " bytes). Aceitar?",
                "Arquivo recebido", JOptionPane.YES_NO_OPTION);
        if (resposta != JOptionPane.YES_OPTION) {
            SwingUtilities.invokeLater(() -> log("Voce recusou o arquivo de " + oferta.remetente + "."));
            return;
        }
        try (Socket direto = new Socket(oferta.ip, oferta.porta)) {
            File pasta = new File("arquivos_recebidos");
            if (!pasta.exists()) {
                pasta.mkdirs();
            }
            File destinoArquivo = new File(pasta, oferta.remetente + "_" + oferta.nomeArquivo);
            try (FileOutputStream saidaArquivo = new FileOutputStream(destinoArquivo)) {
                direto.getInputStream().transferTo(saidaArquivo);
            }
            SwingUtilities.invokeLater(() -> log("[arquivo] Recebido diretamente de " + oferta.remetente
                    + ": " + destinoArquivo.getPath()));
        } catch (IOException ex) {
            SwingUtilities.invokeLater(() -> log("[arquivo] Erro ao baixar de " + oferta.remetente + ": " + ex.getMessage()));
        }
    }

    // fica esperando o outro cliente conectar direto pra so entao mandar o arquivo
    private void aguardarConexaoDireta(ServerSocket servidorArquivo, File arquivo, String destino) {
        try (ServerSocket ss = servidorArquivo; Socket conexaoDireta = ss.accept()) {
            Files.copy(arquivo.toPath(), conexaoDireta.getOutputStream());
            SwingUtilities.invokeLater(() ->
                    log("[arquivo] \"" + arquivo.getName() + "\" enviado diretamente para " + destino + "."));
        } catch (IOException ex) {
            SwingUtilities.invokeLater(() ->
                    log("[arquivo] " + destino + " nao aceitou/conectou a tempo: " + ex.getMessage()));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaChat.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquivo;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPrivada;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel lblApelido;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JPanel painelBaixo;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDestino;
    private javax.swing.JPanel painelTopo;
    private javax.swing.JScrollPane scrollChat;
    private javax.swing.JTextArea taChat;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfMensagem;
    // End of variables declaration//GEN-END:variables
}
