package com.mycompany.atividadeaula6chat;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.nio.file.Files;
import java.util.Base64;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 * ============================================================================
 * TELA (cliente) do chat TCP -- JFrame Form, igual as telas da aula
 * (TelaHello, TelaBusca, TelaCliente): você pode abrir esta classe no
 * NetBeans e usar a aba "Design" pra mexer no layout, igual sempre fez.
 * ============================================================================
 *
 * COMO O CHAT FUNCIONA (pra explicar na defesa):
 *
 * 1) PROTOCOLO -- ver Mensagem.java. Cada linha que passa pelo socket é um
 *    JSON {"tipo":..., "remetente":..., "destino":..., "texto":...}.
 *
 * 2) POR QUE UMA THREAD SEPARADA PRA RECEBER (ver conectar() e
 *    receberMensagens()) -- o requisito da atividade diz "o cliente deve
 *    continuar recebendo mensagens enquanto o usuário digita". O método
 *    entrada.readLine() BLOQUEIA esperando o servidor mandar algo. Se isso
 *    rodasse na thread da tela (a mesma que desenha os botões), a janela
 *    inteira travaria toda vez que não tivesse mensagem chegando. Por isso a
 *    leitura roda numa Thread por conta própria, do mesmo jeito do Coringa
 *    10 (SwingWorker/Thread + invokeLater) da Aula 1.
 *
 * 3) SwingUtilities.invokeLater -- componentes Swing (JTextArea etc.) só
 *    podem ser alterados pela thread da interface gráfica (a "Event
 *    Dispatch Thread"). Como a mensagem chega numa thread diferente (a de
 *    leitura), toda atualização da tela precisa ser "empacotada" com
 *    invokeLater, que entrega esse pedaço de código pra thread certa
 *    executar.
 *
 * 4) A Região Crítica (a lista de usuários conectados) fica no SERVIDOR,
 *    não aqui -- ver ServidorChat.java e TarefaCliente.java.
 *
 * @author jonas
 */
public class TelaChat extends javax.swing.JFrame {

    private Socket socket;
    private PrintWriter saida;
    private String apelido;

    /**
     * Creates new form TelaChat
     */
    public TelaChat() {
        initComponents();
        atualizarEstadoConectado(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTopo = new javax.swing.JPanel();
        lblApelido = new javax.swing.JLabel();
        tfApelido = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        scrollChat = new javax.swing.JScrollPane();
        taChat = new javax.swing.JTextArea();
        painelBaixo = new javax.swing.JPanel();
        painelDestino = new javax.swing.JPanel();
        lblDestino = new javax.swing.JLabel();
        tfDestino = new javax.swing.JTextField();
        tfMensagem = new javax.swing.JTextField();
        painelBotoes = new javax.swing.JPanel();
        btnTodos = new javax.swing.JButton();
        btnPrivada = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnArquivo = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat TCP");
        getContentPane().setLayout(new java.awt.BorderLayout());

        lblApelido.setText("Apelido:");
        painelTopo.add(lblApelido);

        tfApelido.setColumns(12);
        painelTopo.add(tfApelido);

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(this::btnConectarActionPerformed);
        painelTopo.add(btnConectar);

        getContentPane().add(painelTopo, java.awt.BorderLayout.NORTH);

        taChat.setEditable(false);
        taChat.setColumns(20);
        taChat.setRows(5);
        taChat.setLineWrap(true);
        scrollChat.setViewportView(taChat);

        getContentPane().add(scrollChat, java.awt.BorderLayout.CENTER);

        painelBaixo.setLayout(new java.awt.BorderLayout());

        lblDestino.setText("Destino (so p/ Privada):");
        painelDestino.add(lblDestino);

        tfDestino.setColumns(10);
        painelDestino.add(tfDestino);

        painelBaixo.add(painelDestino, java.awt.BorderLayout.NORTH);

        tfMensagem.addActionListener(this::tfMensagemActionPerformed);
        painelBaixo.add(tfMensagem, java.awt.BorderLayout.CENTER);

        btnTodos.setText("Enviar Todos");
        btnTodos.addActionListener(this::btnTodosActionPerformed);
        painelBotoes.add(btnTodos);

        btnPrivada.setText("Enviar Privada");
        btnPrivada.addActionListener(this::btnPrivadaActionPerformed);
        painelBotoes.add(btnPrivada);

        btnListar.setText("Listar");
        btnListar.addActionListener(this::btnListarActionPerformed);
        painelBotoes.add(btnListar);

        btnArquivo.setText("Enviar Arquivo");
        btnArquivo.addActionListener(this::btnArquivoActionPerformed);
        painelBotoes.add(btnArquivo);

        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);
        painelBotoes.add(btnSair);

        painelBaixo.add(painelBotoes, java.awt.BorderLayout.SOUTH);

        getContentPane().add(painelBaixo, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ========================================================================
    // EVENTOS DOS BOTOES (o NetBeans cria estes metodos com duplo clique)
    // ========================================================================

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        conectar();
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        enviarTodos();
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnPrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrivadaActionPerformed
        enviarPrivada();
    }//GEN-LAST:event_btnPrivadaActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquivoActionPerformed
        enviarArquivo();
    }//GEN-LAST:event_btnArquivoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        sair();
    }//GEN-LAST:event_btnSairActionPerformed

    private void tfMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMensagemActionPerformed
        enviarTodos(); // Enter no campo de mensagem = enviar pra todos
    }//GEN-LAST:event_tfMensagemActionPerformed

    // ========================================================================
    // LOGICA DO CHAT (nao gerado pelo NetBeans -- escrito por nos)
    // ========================================================================

    // habilita/desabilita os controles de acordo com o estado da conexao
    private void atualizarEstadoConectado(boolean conectado) {
        tfApelido.setEnabled(!conectado);
        btnConectar.setEnabled(!conectado);
        tfDestino.setEnabled(conectado);
        tfMensagem.setEnabled(conectado);
        btnTodos.setEnabled(conectado);
        btnPrivada.setEnabled(conectado);
        btnListar.setEnabled(conectado);
        btnArquivo.setEnabled(conectado);
        btnSair.setEnabled(conectado);
    }

    private void log(String texto) {
        taChat.append(texto + "\n");
    }

    /** Abre o Socket TCP com o servidor e manda o apelido (1a linha da conexao). */
    private void conectar() {
        apelido = tfApelido.getText().trim();
        if (apelido.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite um apelido.");
            return;
        }
        try {
            socket = new Socket("localhost", 9999);
            saida = new PrintWriter(socket.getOutputStream(), true);
            BufferedReader entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            saida.println(apelido); // 1a linha da conexao = apelido (ver TarefaCliente)

            // Thread separada SO para ficar recebendo mensagens do servidor,
            // pra nao travar a tela enquanto o usuario digita (ver o
            // comentario da classe, no topo do arquivo).
            new Thread(() -> receberMensagens(entrada)).start();

            atualizarEstadoConectado(true);
            log("Conectado como " + apelido + ". Use os botoes abaixo.");
        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nao foi possivel conectar: " + ex.getMessage());
        }
    }

    /** Roda inteira dentro da THREAD DE LEITURA (nunca na thread da tela). */
    private void receberMensagens(BufferedReader entrada) {
        try {
            String linha;
            while ((linha = entrada.readLine()) != null) {
                Mensagem msg = Mensagem.fromLinha(linha);
                String texto = formatar(msg);
                // Aqui e onde o invokeLater entra: "texto" foi montado nesta
                // thread, mas quem escreve na JTextArea tem que ser a EDT.
                SwingUtilities.invokeLater(() -> log(texto));
            }
        } catch (IOException ex) {
            SwingUtilities.invokeLater(() -> {
                log("Conexao encerrada.");
                atualizarEstadoConectado(false);
            });
        }
    }

    private String formatar(Mensagem msg) {
        if ("RESPOSTA".equals(msg.tipo) && msg.lista != null) {
            return "Usuarios conectados: " + msg.lista;
        }
        if ("ERRO".equals(msg.tipo)) {
            return "[ERRO] " + msg.texto;
        }
        if ("PRIVADA".equals(msg.tipo)) {
            return "(privado) " + msg.remetente + ": " + msg.texto;
        }
        if ("ARQUIVO".equals(msg.tipo)) {
            return salvarArquivoRecebido(msg);
        }
        return msg.remetente + ": " + msg.texto;
    }

    /**
     * Requisito bonus: "transferencia direta de arquivo entre clientes".
     * Decodifica o Base64 que veio em msg.dadosArquivo e grava o arquivo na
     * pasta "arquivos_recebidos" (criada do lado de quem recebe, ao lado do
     * projeto). Roda na THREAD DE LEITURA (nao na EDT), mas escrever em
     * disco nao mexe em nenhum componente Swing, entao nao precisa de
     * invokeLater aqui -- so o texto que aparece no chat que precisa.
     */
    private String salvarArquivoRecebido(Mensagem msg) {
        try {
            byte[] dados = Base64.getDecoder().decode(msg.dadosArquivo);
            File pasta = new File("arquivos_recebidos");
            if (!pasta.exists()) {
                pasta.mkdirs();
            }
            File destino = new File(pasta, msg.remetente + "_" + msg.nomeArquivo);
            try (FileOutputStream fos = new FileOutputStream(destino)) {
                fos.write(dados);
            }
            return "[arquivo] " + msg.remetente + " enviou \"" + msg.nomeArquivo
                    + "\" -> salvo em " + destino.getPath();
        } catch (IOException | IllegalArgumentException ex) {
            return "[arquivo] Erro ao receber arquivo de " + msg.remetente + ": " + ex.getMessage();
        }
    }

    /** Requisito: "Enviar mensagem para todos os usuarios conectados". */
    private void enviarTodos() {
        String texto = tfMensagem.getText().trim();
        if (texto.isEmpty()) {
            return;
        }
        saida.println(new Mensagem("BROADCAST", apelido, null, texto).paraLinha());
        tfMensagem.setText("");
    }

    /** Requisito: "Enviar mensagem privada para um usuario especifico". */
    private void enviarPrivada() {
        String destino = tfDestino.getText().trim();
        String texto = tfMensagem.getText().trim();
        if (destino.isEmpty() || texto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha o destino e a mensagem.");
            return;
        }
        saida.println(new Mensagem("PRIVADA", apelido, destino, texto).paraLinha());
        tfMensagem.setText("");
    }

    /**
     * Requisito bonus (+1,0): "transferencia direta de arquivo entre
     * clientes". Reaproveita a MESMA rota da mensagem privada (ver
     * Mensagem.java e ServidorChat.enviarPrivada) -- so troca o "texto" por
     * um arquivo inteiro convertido em Base64.
     */
    private void enviarArquivo() {
        String destino = tfDestino.getText().trim();
        if (destino.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha o destino (apelido de quem vai receber).");
            return;
        }
        JFileChooser seletor = new JFileChooser();
        int escolha = seletor.showOpenDialog(this);
        if (escolha != JFileChooser.APPROVE_OPTION) {
            return; // usuario cancelou
        }
        File arquivo = seletor.getSelectedFile();
        try {
            // Le o arquivo inteiro como bytes e transforma em texto Base64,
            // porque o protocolo so manda TEXTO (uma linha por println/readLine).
            byte[] dados = Files.readAllBytes(arquivo.toPath());
            String base64 = Base64.getEncoder().encodeToString(dados);
            saida.println(Mensagem.novoArquivo(apelido, destino, arquivo.getName(), base64).paraLinha());
            log("Voce enviou o arquivo \"" + arquivo.getName() + "\" para " + destino + ".");
        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nao foi possivel ler o arquivo: " + ex.getMessage());
        }
    }

    /** Requisito: "Ver a lista dos usuarios logados no momento". */
    private void listar() {
        saida.println(new Mensagem("LISTAR", apelido, null, null).paraLinha());
    }

    /** Requisito: "Sair do chat, avisando os demais usuarios". */
    private void sair() {
        try {
            saida.println(new Mensagem("SAIR", apelido, null, null).paraLinha());
            socket.close();
        } catch (IOException ex) {
            // ja estava fechando mesmo, pode ignorar
        }
        atualizarEstadoConectado(false);
        log("Voce saiu do chat.");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaChat.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquivo;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPrivada;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel lblApelido;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JPanel painelBaixo;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDestino;
    private javax.swing.JPanel painelTopo;
    private javax.swing.JScrollPane scrollChat;
    private javax.swing.JTextArea taChat;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfMensagem;
    // End of variables declaration//GEN-END:variables
}
